# Generated by Django 4.0 on 2022-01-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_itemdetail_options_itemdetail_timeadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='item_status',
            field=models.CharField(choices=[('Found', 'Found'), ('Lost', 'Lost')], default='Lost', max_length=30, null=True, verbose_name='Items Status'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='dateFL',
            field=models.DateField(verbose_name='Date Found/Lost'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='description',
            field=models.TextField(verbose_name='Item Details'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Item Image'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
    ]
