# Generated by Django 4.0 on 2022-01-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetail',
            old_name='host',
            new_name='owner',
        ),
    ]
